### PR TITLE
Upgrade version of princexml to 13.5 and support ubuntu 20.04 focal

### PR DESCRIPTION
**Pull request by stefanvandekaa**

### CODE REVIEW

**Comment by stefanvandekaa** [comment]
@greatislander and @fullyint, is there a way we can get this merged?

**Comment by greatislander** [comment]
@stefanvandekaa I can't speak for the Pressbooks project but I don't think they use this anymore so it's not likely that the team will be able to spend time reviewing this. @SteelWagstaff, is that the case?

I'd suggest forking this role if you'd like to use it, @stefanvandekaa— and the @SteelWagstaff, the Pressbooks role should probably be archived and marked as deprecated (see: https://galaxy.ansible.com/docs/contributing/deprecate.html).

**Comment by SteelWagstaff** [comment]
@stefanvandekaa, @greatislander is correct, we don't use this repo anymore. We will archive & deprecate this role at some point in the future. Sorry we weren't able to review your PR as quickly as you would have liked.

**Comment by SteelWagstaff** [comment]
@stefanvandekaa, we've deprecated the Ansible role and will be archiving this repo shortly as we're no longer using or maintaining either. Please do feel free to fork the role and do whatever you'd like with it if you find it useful.

**Pull request closed without merging**
